/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker/worker-configuration.d.ts` (hash: 61a9aedb0dfedb5ae452fd4e1c3a4c24)
interface __BaseEnv_Env {
	DB: D1Database;
	PLACES_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APP_NAME: "coffee-review";
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUD: "";
	DEV_USER_EMAIL: string;
	GOOGLE_MAPS_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "DEV_USER_EMAIL" | "GOOGLE_MAPS_API_KEY">> {}
}
